"""book chunk origin column — section 11 auditability

Records where each chunk's text came from: "text" is public-domain prose from
Project Gutenberg, "description" is a third-party blurb from a metadata
provider. Section 11 requires the licensing basis of every stored passage to
be explicit, and once both kinds live in one table there is otherwise no way
to tell them apart after the fact.

server_default is not optional here (F-28): a NOT NULL column added without
one fails against any populated table, and this table already holds 25,898
rows. Existing rows are all Gutenberg text, so "text" is the correct backfill
rather than a placeholder.

Rollback: `alembic downgrade 9c52a14216cc` drops the column. No data is lost
that cannot be recomputed by rechunking.

Revision ID: 61725c6a5590
Revises: 9c52a14216cc
Create Date: 2026-08-29 20:56:15.584057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61725c6a5590'
down_revision: Union[str, Sequence[str], None] = '9c52a14216cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_chunks', sa.Column('origin', sa.String(length=16), server_default='text', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_chunks', 'origin')
    # ### end Alembic commands ###
