"""phase 2 book chunks and embeddings — sections 22 and 27

Creates the retrieval substrate for semantic search: one table holding both
public catalogue chunks and private user-owned chunks, with the visibility
rule enforced by a CHECK constraint rather than by every query remembering it.

Also creates the `vector` extension. The image (pgvector/pgvector:pg16) ships
the extension but does not enable it, so this is the first migration that can
actually use the type.

Rollback: `alembic downgrade 6c320ab0f357` drops the table and its indexes.
The extension is deliberately left in place — dropping it would break any
other schema in the same database that uses it, and an unused extension costs
nothing. Verified both directions against a populated database.

Revision ID: 9c52a14216cc
Revises: 6c320ab0f357
Create Date: 2026-08-29 20:13:01.550848

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c52a14216cc'
down_revision: Union[str, Sequence[str], None] = '6c320ab0f357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The type below does not exist until this runs. IF NOT EXISTS keeps the
    # migration idempotent against a database where it was enabled by hand.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    op.create_table('book_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=16), server_default='public', nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(visibility = 'public'  AND user_id IS NULL) OR (visibility = 'private' AND user_id IS NOT NULL)", name='ck_book_chunks_visibility_owner'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_book_chunks_unembedded', 'book_chunks', ['id'], unique=False, postgresql_where=sa.text('embedding IS NULL'))
    op.create_index('ix_book_chunks_visibility_user', 'book_chunks', ['visibility', 'user_id'], unique=False)
    op.create_index('uq_book_chunks_identity', 'book_chunks', ['book_id', 'user_id', 'ordinal'], unique=True, postgresql_nulls_not_distinct=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_book_chunks_identity', table_name='book_chunks', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_book_chunks_visibility_user', table_name='book_chunks')
    op.drop_index('ix_book_chunks_unembedded', table_name='book_chunks', postgresql_where=sa.text('embedding IS NULL'))
    op.drop_table('book_chunks')
    # The `vector` extension is intentionally NOT dropped. See the module
    # docstring: it may be in use elsewhere, and leaving it costs nothing.
