"""phase 2: isbn columns and enrichment tracking

Revision ID: cc9a7acaa268
Revises: 41fca51e775f
Create Date: 2026-08-19 14:13:11.113723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9a7acaa268'
down_revision: Union[str, Sequence[str], None] = '41fca51e775f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('isbn_10', sa.String(length=10), nullable=True))
    op.add_column('books', sa.Column('isbn_13', sa.String(length=13), nullable=True))
    op.add_column('books', sa.Column('enrichment_status', sa.String(length=16), nullable=False))
    op.add_column('books', sa.Column('enrichment_source', sa.String(length=32), nullable=True))
    op.add_column('books', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_books_enrichment_pending', 'books', ['enrichment_status'], unique=False, postgresql_where=sa.text("enrichment_status = 'pending'"))
    op.create_index('ix_books_isbn_10', 'books', ['isbn_10'], unique=False)
    op.create_index('ix_books_isbn_13', 'books', ['isbn_13'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_books_isbn_13', table_name='books')
    op.drop_index('ix_books_isbn_10', table_name='books')
    op.drop_index('ix_books_enrichment_pending', table_name='books', postgresql_where=sa.text("enrichment_status = 'pending'"))
    op.drop_column('books', 'enriched_at')
    op.drop_column('books', 'enrichment_source')
    op.drop_column('books', 'enrichment_status')
    op.drop_column('books', 'isbn_13')
    op.drop_column('books', 'isbn_10')
    # ### end Alembic commands ###
