"""book_vectors: one embedding per book (F-44)

Revision ID: faaa9c1a2d93
Revises: 61725c6a5590
Create Date: 2026-08-31 11:18:40.429507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'faaa9c1a2d93'
down_revision: Union[str, Sequence[str], None] = '61725c6a5590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_vectors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('embedding_model', sa.String(length=64), nullable=True),
    sa.Column('has_description', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source_chars', sa.Integer(), nullable=True),
    sa.Column('built_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_vectors')
    # ### end Alembic commands ###
